import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export interface MergeInput {
  label: string;
  bytes: Uint8Array;
}

export interface MergeOptions {
  coverTitle?: string | undefined;
  coverSubtitle?: string | undefined;
  addPageNumbers?: boolean | undefined;
}

export async function mergePdfs(
  inputs: MergeInput[],
  options?: MergeOptions,
): Promise<Uint8Array> {
  const merged = await PDFDocument.create();
  const font = await merged.embedFont(StandardFonts.Helvetica);
  const fontBold = await merged.embedFont(StandardFonts.HelveticaBold);

  // Cover page if title provided
  if (options?.coverTitle) {
    const coverPage = merged.addPage([612, 792]); // US Letter
    const { height } = coverPage.getSize();

    coverPage.drawText(options.coverTitle, {
      x: 72,
      y: height - 120,
      size: 24,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.1),
    });

    if (options.coverSubtitle) {
      coverPage.drawText(options.coverSubtitle, {
        x: 72,
        y: height - 155,
        size: 14,
        font,
        color: rgb(0.3, 0.3, 0.3),
      });
    }

    // Table of contents
    coverPage.drawText("Contents", {
      x: 72,
      y: height - 210,
      size: 16,
      font: fontBold,
    });

    let tocY = height - 240;
    for (let i = 0; i < inputs.length; i++) {
      coverPage.drawText(`${i + 1}. ${inputs[i]!.label}`, {
        x: 90,
        y: tocY,
        size: 12,
        font,
      });
      tocY -= 22;
    }

    // Footer
    coverPage.drawText("Generated by PigeonGov", {
      x: 72,
      y: 50,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
  }

  // Merge all PDFs
  for (const input of inputs) {
    const source = await PDFDocument.load(input.bytes);
    const pages = await merged.copyPages(source, source.getPageIndices());
    for (const page of pages) {
      merged.addPage(page);
    }
  }

  return merged.save();
}
