import type { Command } from "commander";

// All registered subcommands
const SUBCOMMANDS = [
  "fill",
  "validate",
  "review",
  "list",
  "extract",
  "deadlines",
  "fees",
  "glossary",
  "life-event",
  "screen",
  "drafts",
  "vault",
  "profile",
  "merge",
  "serve",
  "doctor",
  "tui",
  "schemas",
  "start",
  "workflows",
  "machine",
  "completions",
  "scaffold",
  "plugins",
  "testdata",
  "stats",
] as const;

// All known workflow IDs for static completion
const WORKFLOW_IDS = [
  "tax/1040",
  "immigration/family-visa-intake",
  "immigration/naturalization",
  "immigration/green-card-renewal",
  "immigration/daca-renewal",
  "immigration/work-authorization",
  "healthcare/aca-enrollment",
  "healthcare/medicare-enrollment",
  "unemployment/claim-intake",
  "business/license-starter",
  "permits/local-permit-planner",
  "education/fafsa",
  "education/student-loan-repayment",
  "identity/passport",
  "identity/name-change",
  "identity/voter-registration",
  "identity/real-id",
  "benefits/snap",
  "benefits/wic",
  "benefits/liheap",
  "benefits/medicaid",
  "benefits/ssdi-application",
  "estate/basic-will",
  "estate/power-of-attorney",
  "estate/advance-directive",
  "veterans/disability-claim",
  "veterans/gi-bill",
  "veterans/va-healthcare",
  "legal/small-claims",
  "legal/expungement",
  "legal/child-support-modification",
  "retirement/ssa-estimator",
] as const;

const DOMAINS = [
  "tax",
  "immigration",
  "healthcare",
  "unemployment",
  "business",
  "permits",
  "education",
  "identity",
  "benefits",
  "estate",
  "veterans",
  "legal",
  "retirement",
] as const;

const GLOBAL_FLAGS = [
  "--json",
  "--jsonl",
  "--compact",
  "--full",
  "--non-interactive",
  "--yes",
  "--dry-run",
  "--quiet",
  "--stdin",
  "--locale",
  "--fields",
] as const;

function generateZshCompletions(): string {
  const workflowList = WORKFLOW_IDS.map((id) => `'${id}'`).join(" ");
  const domainList = DOMAINS.map((d) => `'${d}'`).join(" ");
  const subcommandDesc = SUBCOMMANDS.map((cmd) => `'${cmd}:Run ${cmd} command'`).join("\n      ");
  const flagArgs = GLOBAL_FLAGS.map((f) => `'${f}[${f.replace(/^--/, "")} option]'`).join("\n      ");

  return `#compdef pigeongov

# Shell completions for pigeongov — generated by \`pigeongov completions zsh\`
# Install: pigeongov completions zsh > ~/.zsh/completions/_pigeongov
# Then add \`fpath=(~/.zsh/completions $fpath)\` to your .zshrc and run \`compinit\`.

_pigeongov_workflows() {
  local -a workflows
  # Try dynamic completion first
  if command -v pigeongov &>/dev/null; then
    workflows=(\${(f)"$(pigeongov list --json --compact 2>/dev/null | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  for w in data.get('workflows', []):
    print(w['id'])
except: pass
" 2>/dev/null)"})
  fi
  # Fall back to static list if dynamic failed
  if [[ \${#workflows[@]} -eq 0 ]]; then
    workflows=(${workflowList})
  fi
  _describe 'workflow' workflows
}

_pigeongov_domains() {
  local -a domains
  domains=(${domainList})
  _describe 'domain' domains
}

_pigeongov() {
  local curcontext="\$curcontext" state line
  typeset -A opt_args

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args' \\
    ${flagArgs}

  case \$state in
    command)
      local -a commands
      commands=(
      ${subcommandDesc}
      )
      _describe 'pigeongov command' commands
      ;;
    args)
      case \$line[1] in
        fill|start)
          _arguments '1:workflow:_pigeongov_workflows' \\
            '--year[Workflow year]:year' \\
            '--output[Output directory]:dir:_files -/' \\
            '--format[Output format]:(json pdf both)' \\
            '--import[Import PDFs]:file:_files -g "*.pdf"' \\
            '--data[JSON data file]:file:_files -g "*.json"' \\
            '--resume[Resume from bundle]:file:_files -g "*.json"' \\
            '--from-bundle[Use saved bundle]:file:_files -g "*.json"' \\
            '--no-interactive[Skip prompts]' \\
            '--no-tui[Disable TUI]' \\
            '--json[JSON output]' \\
            '--quiet[Suppress output]'
          ;;
        list)
          _arguments \\
            '--domain[Filter by domain]:domain:_pigeongov_domains' \\
            '--json[JSON output]'
          ;;
        validate|review|extract)
          _arguments '1:file:_files -g "*.json"'
          ;;
        completions)
          _arguments '1:shell:(zsh bash fish)'
          ;;
        drafts)
          _arguments '1:subcommand:(list delete cleanup)'
          ;;
        vault)
          _arguments '1:subcommand:(store list get delete)'
          ;;
        profile)
          _arguments '1:subcommand:(show set clear)'
          ;;
        schemas)
          _arguments '1:workflow:_pigeongov_workflows'
          ;;
        *)
          _default
          ;;
      esac
      ;;
  esac
}

_pigeongov "\$@"
`;
}

function generateBashCompletions(): string {
  const workflowList = WORKFLOW_IDS.join(" ");
  const domainList = DOMAINS.join(" ");
  const subcommandList = SUBCOMMANDS.join(" ");
  const flagList = GLOBAL_FLAGS.join(" ");

  return `# Bash completions for pigeongov — generated by \`pigeongov completions bash\`
# Install: pigeongov completions bash > /etc/bash_completion.d/pigeongov
# Or: pigeongov completions bash >> ~/.bashrc

_pigeongov_get_workflows() {
  local workflows
  if command -v pigeongov &>/dev/null; then
    workflows="$(pigeongov list --json --compact 2>/dev/null | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  for w in data.get('workflows', []):
    print(w['id'])
except: pass
" 2>/dev/null)"
  fi
  if [[ -z "$workflows" ]]; then
    workflows="${workflowList}"
  fi
  echo "$workflows"
}

_pigeongov_completions() {
  local cur prev words cword
  _init_completion || return

  local subcommands="${subcommandList}"
  local global_flags="${flagList}"
  local domains="${domainList}"

  # Complete global flags anywhere
  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "\${global_flags}" -- "\${cur}") )
    return
  fi

  # First argument: subcommand
  if [[ \${cword} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${subcommands}" -- "\${cur}") )
    return
  fi

  # Subcommand-specific completions
  local subcmd="\${words[1]}"
  case "\${subcmd}" in
    fill|start)
      if [[ \${cword} -eq 2 ]]; then
        local workflows
        workflows="$(_pigeongov_get_workflows)"
        COMPREPLY=( $(compgen -W "\${workflows}" -- "\${cur}") )
        return
      fi
      case "\${prev}" in
        --format)
          COMPREPLY=( $(compgen -W "json pdf both" -- "\${cur}") )
          return
          ;;
        --output)
          COMPREPLY=( $(compgen -d -- "\${cur}") )
          return
          ;;
        --data|--resume|--from-bundle)
          COMPREPLY=( $(compgen -f -X '!*.json' -- "\${cur}") )
          return
          ;;
        --import)
          COMPREPLY=( $(compgen -f -X '!*.pdf' -- "\${cur}") )
          return
          ;;
      esac
      COMPREPLY=( $(compgen -W "--year --output --format --import --data --resume --from-bundle --no-interactive --no-tui --json --quiet" -- "\${cur}") )
      ;;
    list)
      case "\${prev}" in
        --domain)
          COMPREPLY=( $(compgen -W "\${domains}" -- "\${cur}") )
          return
          ;;
      esac
      COMPREPLY=( $(compgen -W "--domain --json" -- "\${cur}") )
      ;;
    validate|review|extract)
      COMPREPLY=( $(compgen -f -- "\${cur}") )
      ;;
    completions)
      if [[ \${cword} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "zsh bash fish" -- "\${cur}") )
      fi
      ;;
    schemas)
      if [[ \${cword} -eq 2 ]]; then
        local workflows
        workflows="$(_pigeongov_get_workflows)"
        COMPREPLY=( $(compgen -W "\${workflows}" -- "\${cur}") )
      fi
      ;;
    drafts)
      if [[ \${cword} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "list delete cleanup" -- "\${cur}") )
      fi
      ;;
    vault)
      if [[ \${cword} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "store list get delete" -- "\${cur}") )
      fi
      ;;
    profile)
      if [[ \${cword} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "show set clear" -- "\${cur}") )
      fi
      ;;
  esac
}

complete -F _pigeongov_completions pigeongov
`;
}

function generateFishCompletions(): string {
  const lines: string[] = [
    "# Fish completions for pigeongov — generated by `pigeongov completions fish`",
    "# Install: pigeongov completions fish > ~/.config/fish/completions/pigeongov.fish",
    "",
    "# Disable file completions by default",
    "complete -c pigeongov -f",
    "",
    "# Dynamic workflow completion function",
    "function __pigeongov_workflows",
    '  set -l workflows (pigeongov list --json --compact 2>/dev/null | python3 -c "',
    "import sys, json",
    "try:",
    "  data = json.load(sys.stdin)",
    "  for w in data.get('workflows', []):",
    "    print(w['id'])",
    'except: pass',
    '" 2>/dev/null)',
    "  if test (count $workflows) -eq 0",
  ];

  // Add static fallback
  for (const id of WORKFLOW_IDS) {
    lines.push(`    echo '${id}'`);
  }

  lines.push(
    "  else",
    "    for w in $workflows",
    "      echo $w",
    "    end",
    "  end",
    "end",
    "",
    "# Condition: no subcommand yet",
    "function __pigeongov_needs_command",
    "  set -l cmd (commandline -opc)",
    "  test (count $cmd) -eq 1",
    "end",
    "",
  );

  // Subcommands
  for (const cmd of SUBCOMMANDS) {
    lines.push(
      `complete -c pigeongov -n '__pigeongov_needs_command' -a '${cmd}' -d 'Run ${cmd} command'`,
    );
  }

  lines.push("");

  // Global flags
  for (const flag of GLOBAL_FLAGS) {
    const name = flag.replace(/^--/, "");
    lines.push(
      `complete -c pigeongov -l '${name}' -d '${name} option'`,
    );
  }

  lines.push("");

  // fill/start: workflow ID argument
  lines.push(
    "# fill and start take a workflow ID as first arg",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -a '(__pigeongov_workflows)' -d 'Workflow ID'",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'year' -d 'Workflow year' -r",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'output' -d 'Output directory' -r -F",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'format' -d 'Output format' -r -a 'json pdf both'",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'import' -d 'Import PDFs' -r -F",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'data' -d 'JSON data file' -r -F",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'resume' -d 'Resume from bundle' -r -F",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'from-bundle' -d 'Use saved bundle' -r -F",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'no-interactive' -d 'Skip prompts'",
    "complete -c pigeongov -n '__fish_seen_subcommand_from fill start' -l 'no-tui' -d 'Disable TUI'",
    "",
  );

  // list: --domain
  const domainList = DOMAINS.join(" ");
  lines.push(
    "# list command",
    `complete -c pigeongov -n '__fish_seen_subcommand_from list' -l 'domain' -d 'Filter by domain' -r -a '${domainList}'`,
    "",
  );

  // completions: shell argument
  lines.push(
    "# completions command",
    "complete -c pigeongov -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish' -d 'Shell type'",
    "",
  );

  // schemas: workflow ID
  lines.push(
    "# schemas command",
    "complete -c pigeongov -n '__fish_seen_subcommand_from schemas' -a '(__pigeongov_workflows)' -d 'Workflow ID'",
    "",
  );

  // drafts subcommands
  lines.push(
    "# drafts subcommands",
    "complete -c pigeongov -n '__fish_seen_subcommand_from drafts' -a 'list delete cleanup' -d 'Drafts operation'",
    "",
  );

  // vault subcommands
  lines.push(
    "# vault subcommands",
    "complete -c pigeongov -n '__fish_seen_subcommand_from vault' -a 'store list get delete' -d 'Vault operation'",
    "",
  );

  // profile subcommands
  lines.push(
    "# profile subcommands",
    "complete -c pigeongov -n '__fish_seen_subcommand_from profile' -a 'show set clear' -d 'Profile operation'",
    "",
  );

  // validate/review/extract: file completion
  lines.push(
    "# validate, review, extract: file arguments",
    "complete -c pigeongov -n '__fish_seen_subcommand_from validate review extract' -F",
  );

  return lines.join("\n") + "\n";
}

export function registerCompletionsCommand(program: Command): void {
  program
    .command("completions")
    .description("Generate shell completion scripts")
    .argument("<shell>", "Shell type: zsh, bash, or fish")
    .action((shell: string) => {
      switch (shell.toLowerCase()) {
        case "zsh":
          console.log(generateZshCompletions());
          break;
        case "bash":
          console.log(generateBashCompletions());
          break;
        case "fish":
          console.log(generateFishCompletions());
          break;
        default:
          console.error(`Unsupported shell: ${shell}. Use zsh, bash, or fish.`);
          process.exitCode = 2;
      }
    });
}
